### ISSUE TITLE
Newsletter/ updates and insights screen

### ISSUE THREAD

**Issue by ST10036066** [IIE-Cape-Tech-Creatives/Phumlani_Dube_Foundation-mobileApp#3]

**Comment by Zuwarashe** [comment]
How to Navigate the Phumulani Dude Foundation Newsletter & Events Page:
Step One: Viewing Newsletter Highlights
At the top of the page, you'll see buttons labeled with different months, such as | August Highlights | and | September Highlights |. These buttons allow you to explore the key events and topics covered each month.

To view topics: Simply tap the button for the month you want to explore. For example, tapping the "August Highlights" button will display topics like Youth Mentorship, Community Clean-Up, and Future Projects.
You can scroll horizontally to explore more months and their respective highlights.
Step Two: Downloading the Newsletter
After viewing the topics for each month, you may want to download the full newsletter for more details.

To download: Scroll down to the Download button located beneath the monthly buttons and tap it. This will download the full newsletter report to your device for easy access.
Step Three: Checking Upcoming Events
Right below the newsletter section, you'll see the Upcoming Events section.

To view events: This section lists the upcoming events, showing the date on the left and a brief description on the right. For example, you may see an event like Oct 20, 2024 - Fundraiser. Scroll through the events to stay informed about future activities.
Step Four: Learning More About Our Organization
At the bottom of the page is an option to learn more about the Phumulani Dude Foundation.

To learn more: Scroll down to the Insights Section and tap the Learn More button. This will direct you to a page with more information about the foundation's mission, projects, and community impact.


![Screenshot 2024-10-13 212517](https://github.com/user-attachments/assets/041d5128-da7c-4e6e-a6e4-36444ec78972)
